#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYNHANVIENBANGLUONG")]
	public partial class SP_ThemNVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SP_ThemNVDataContext() : 
				base(global::PayrollManagement.Properties.Settings.Default.QUANLYNHANVIENBANGLUONGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SP_ThemNVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SP_ThemNVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SP_ThemNVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SP_ThemNVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Them_NhanVien")]
		public int SP_Them_NhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenNV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngayKyHD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HSLuong", DbType="Float")] System.Nullable<double> hSLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuongCB", DbType="Float")] System.Nullable<double> luongCB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phanQuyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenNV, username, password, sdt, email, gioiTinh, ngaySinh, ngayKyHD, hSLuong, luongCB, idCV, idPB, idTD, idHD, phanQuyen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CapNhat_NhanVien")]
		public int SP_CapNhat_NhanVien(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNV, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenNV, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string gioiTinh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaySinh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngayKyHD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HSLuong", DbType="Float")] System.Nullable<double> hSLuong, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuongCB", DbType="Float")] System.Nullable<double> luongCB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCV, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idHD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phanQuyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNV, tenNV, username, password, sdt, email, gioiTinh, ngaySinh, ngayKyHD, hSLuong, luongCB, idCV, idPB, idTD, idHD, phanQuyen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Xoa_NhanVien")]
		public int SP_Xoa_NhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Them_PB")]
		public int SP_Them_PB([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenPB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenPB);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CapNhat_PB")]
		public int SP_CapNhat_PB([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenPB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPB, tenPB);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Xoa_PB")]
		public int SP_Xoa_PB([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Them_CV")]
		public int SP_Them_CV([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenCV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenCV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CapNhat_CV")]
		public int SP_CapNhat_CV([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenCV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCV, tenCV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Xoa_CV")]
		public int SP_Xoa_CV([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Xoa_TD")]
		public int SP_Xoa_TD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Them_TD")]
		public int SP_Them_TD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenTD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenTD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CapNhat_TD")]
		public int SP_CapNhat_TD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenTD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTD, tenTD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CapNhat_HD")]
		public int SP_CapNhat_HD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string loaiHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thoiHan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idHD, tenHD, loaiHD, thoiHan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Them_HD")]
		public int SP_Them_HD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string tenHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string loaiHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thoiHan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenHD, loaiHD, thoiHan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Xoa_HD")]
		public int SP_Xoa_HD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Xoa_ChamCong")]
		public int SP_Xoa_ChamCong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CapNhat_ChamCong")]
		public int SP_CapNhat_ChamCong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoNgayLamViec", DbType="Int")] System.Nullable<int> soNgayLamViec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoNgayLamThem", DbType="Int")] System.Nullable<int> soNgayLamThem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoGioTangCa", DbType="Int")] System.Nullable<int> soGioTangCa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLanDiTre", DbType="Int")] System.Nullable<int> soLanDiTre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLuong, idNV, nam, thang, soNgayLamViec, soNgayLamThem, soGioTangCa, soLanDiTre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Them_ChamCong")]
		public int SP_Them_ChamCong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoNgayLamViec", DbType="Int")] System.Nullable<int> soNgayLamViec, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoNgayLamThem", DbType="Int")] System.Nullable<int> soNgayLamThem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoGioTangCa", DbType="Int")] System.Nullable<int> soGioTangCa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLanDiTre", DbType="Int")] System.Nullable<int> soLanDiTre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNV, nam, thang, soNgayLamViec, soNgayLamThem, soGioTangCa, soLanDiTre);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
